trigger: none

pr:
  branches:
    include:
    - main
    - releases/*
  paths:
    include:
    - e2e_samples/parking_sensors_synapse/src/ddo_transform/*

variables:
  pythonWorkingDir: 'e2e_samples/parking_sensors_synapse/src/ddo_transform'

pool:
  vmImage: 'Ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
<<<<<<< HEAD
    versionSpec: '3.8'
=======
    versionSpec: '3.6'
>>>>>>> f06c799 (fix(parking_sensors_synapse): clarity in README in parking sensor synapse sample, add requirement for Synapse extension, comment out debugging in script by default, add general troubleshooting section (#466))
    architecture: 'x64'

- script: pip install -r requirements_dev.txt && pip install -r requirements.txt
  workingDirectory: $(pythonWorkingDir)
  displayName: 'Install requirements'

- script: make lint && make test
  workingDirectory: $(pythonWorkingDir)
  displayName: 'Run lint tests'
